/****************** Clients Table***********************/

--- CREATE TABLE DESIG

CREATE TABLE Clients
(
   Client_ID        NUMBER (5) CONSTRAINT CL_ID_PK PRIMARY KEY,
   Client_name      VARCHAR2 (50) CONSTRAINT CL_NAME_NN NOT NULL,
   Client_Address   VARCHAR2 (50) CONSTRAINT CL_ADD_NN NOT NULL,
   Client_Notes     VARCHAR2 (50)
);

-- CREATE CLIENT ID SEQUENCE

CREATE SEQUENCE CLIENTS_ID_SEQ
   START WITH 1
   INCREMENT BY 1
   MAXVALUE 10000
   MINVALUE 1
   NOCYCLE
   NOORDER;

-- CREATE TRIGGER ON CLIENT ID SEQUENCE ON CLIENTS TABLE

CREATE OR REPLACE TRIGGER CLIENT_ID_TRG
   BEFORE INSERT
   ON HR.Clients
   REFERENCING NEW AS New OLD AS Old
   FOR EACH ROW
BEGIN
   :NEW.Client_ID := CLIENTS_ID_SEQ.NEXTVAL;
END CLIENT_ID_TRG;


-- CREATE CLIENT INSERTION PROCEDURE 

CREATE OR REPLACE PROCEDURE CLIENT_INSERTION (CLT_NAME  VARCHAR2, CLT_ADD  VARCHAR2)
AS
BEGIN

   INSERT INTO Clients (Client_name, Client_Address)
        VALUES (CLT_NAME, CLT_ADD);
END;

SHOW ERRORS;

